package gui;

import dao.ClienteDao;

import dao.EnderecoDao;
import dao.PedidoDao;
import dao.ProdutoDao;
import dao.TransportadoraDao;
import dao.VendedorDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import models.Cliente;

import models.Endereco;
import models.Pedido;
import models.Produto;
import models.Transportadora;
import models.Vendedor;

/**
 *
 * @author Jefeson
 */
public class PedidoConsultarSub extends javax.swing.JFrame {

    private final long codigoPedido;
    private final long codigoVendedor;

    /**
     * Creates new form PedidoConsultarSub
     *
     * @param codigoPedido
     * @param codigoVendedor
     */
    public PedidoConsultarSub(long codigoPedido, long codigoVendedor) {

        initComponents();
        this.codigoPedido = codigoPedido;
        this.codigoVendedor = codigoVendedor;
        Pedido p = null;
        try {
            p = PedidoDao.readByCodigoPedido(codigoPedido);

            txtCodigoCliente.setText("" + p.getCliente().getCodigo());
            txtPrimeiroNomeCliente.setText(p.getCliente().getPrimeiroNome());
            txtNomeDoMeioCliente.setText(p.getCliente().getNomeDoMeio());
            txtSobrenomeCliente.setText(p.getCliente().getSobrenome());
            txtSufixoCliente.setText(p.getCliente().getSufixo());
            txtTratamentoCliente.setText(p.getCliente().getTratamento());

            txtLogradouroFatura.setText(p.getEnderecoFatura().getLogradouro() + " " + p.getEnderecoFatura().getComplemento());
            txtCidadeFatura.setText(p.getEnderecoFatura().getCidade());
            txtEstadoFatura.setText(p.getEnderecoFatura().getEstado());
            txtPaisFatura.setText(p.getEnderecoFatura().getPais());
            txtCodigoPostalFatura.setText(p.getEnderecoFatura().getCodigopostal());

            txtLogradouroEntrega.setText(p.getEnderecoEntrega().getLogradouro() + " " + p.getEnderecoEntrega().getComplemento());
            txtCidadeEntrega.setText(p.getEnderecoEntrega().getCidade());
            txtEstadoEntrega.setText(p.getEnderecoEntrega().getEstado());
            txtPaisEntrega.setText(p.getEnderecoEntrega().getPais());
            txtCodigoPostalEntrega.setText(p.getEnderecoEntrega().getCodigopostal());

            txtNomeTransportadora.setText(p.getTrasportadora().getNome());
            txtTaxaBaseTransportadora.setText("" + p.getTrasportadora().getTaxaBase());
            txtTaxaBaseEnvioTransportadora.setText("" + p.getTrasportadora().getTaxaEnvio());

            txtCodigoVendedor.setText("" + p.getVendedor().getCodigo());
            txtNomeVendedor.setText(p.getVendedor().getPrimeiroNome() + " " + p.getVendedor().getNomeDoMeio() + " " + p.getVendedor().getSobrenome());

            txtDtPedido.setText("" + p.getDtpedido());

            txtContaCliente.setText(p.getContaCliente());
            txtNumeroCartaoCredito.setText("" + p.getNumeroCartaoCredito());
            txtCodigoConfirmacao.setText(p.getCodigoConfirmacao());

//            List<DetalhesPedido> dp = null;
//            dp = DetalhesPedidoDao.readProduto(p.getCodigo()+"");
//            
            
            DefaultTableModel modeloTable = (DefaultTableModel) tbProdutos.getModel();
            modeloTable.setNumRows(0);

            for (Produto prod : p.getProdutos()) {
                modeloTable.addRow(new Object[]{
                    prod.getQuantidade(),
                    prod.getCodigo(),
                    prod.getNome(),
                    prod.getPreco(),
                    prod.getCor(),
                    prod.getCategoria(),
                    prod.getTamanho(),
                    prod.getPeso()
                });
            }
            txtTotal.setText("$ "+p.somarPedido()+"");
        } catch (SQLException ex) {
            Logger.getLogger(PedidoConsultarSub.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtPrimeiroNomeCliente = new javax.swing.JTextField();
        txtNomeDoMeioCliente = new javax.swing.JTextField();
        txtSobrenomeCliente = new javax.swing.JTextField();
        txtTratamentoCliente = new javax.swing.JTextField();
        txtNomeVendedor = new javax.swing.JTextField();
        txtCodigoVendedor = new javax.swing.JTextField();
        txtSufixoCliente = new javax.swing.JTextField();
        txtDtPedido = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtLogradouroFatura = new javax.swing.JTextField();
        txtCidadeFatura = new javax.swing.JTextField();
        txtPaisFatura = new javax.swing.JTextField();
        txtEstadoFatura = new javax.swing.JTextField();
        txtCodigoPostalFatura = new javax.swing.JTextField();
        txtNumeroCartaoCredito = new javax.swing.JTextField();
        txtContaCliente = new javax.swing.JTextField();
        txtCodigoConfirmacao = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtNomeTransportadora = new javax.swing.JTextField();
        txtTaxaBaseTransportadora = new javax.swing.JTextField();
        txtTaxaBaseEnvioTransportadora = new javax.swing.JTextField();
        txtLogradouroEntrega = new javax.swing.JTextField();
        txtCidadeEntrega = new javax.swing.JTextField();
        txtEstadoEntrega = new javax.swing.JTextField();
        txtPaisEntrega = new javax.swing.JTextField();
        txtCodigoPostalEntrega = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel2.setPreferredSize(new java.awt.Dimension(609, 345));
        jPanel2.setRequestFocusEnabled(false);

        txtCodigoCliente.setEditable(false);
        txtCodigoCliente.setText("codigo");

        txtPrimeiroNomeCliente.setEditable(false);
        txtPrimeiroNomeCliente.setText("primeiroNome");
        txtPrimeiroNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimeiroNomeClienteActionPerformed(evt);
            }
        });

        txtNomeDoMeioCliente.setEditable(false);
        txtNomeDoMeioCliente.setText("nomeDoMeio");

        txtSobrenomeCliente.setEditable(false);
        txtSobrenomeCliente.setText("sobrenome");

        txtTratamentoCliente.setEditable(false);
        txtTratamentoCliente.setText("tratamento");

        txtNomeVendedor.setEditable(false);
        txtNomeVendedor.setText("nomeVendedor");

        txtCodigoVendedor.setEditable(false);
        txtCodigoVendedor.setText("codigoVendedor");

        txtSufixoCliente.setEditable(false);
        txtSufixoCliente.setText("sufixo");

        txtDtPedido.setEditable(false);
        txtDtPedido.setText("dtPedido");

        txtTotal.setEditable(false);
        txtTotal.setText("total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSufixoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTratamentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeDoMeioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrimeiroNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDtPedido))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrimeiroNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeDoMeioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTratamentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSufixoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(591, 345));

        txtLogradouroFatura.setEditable(false);
        txtLogradouroFatura.setText("logradouro");

        txtCidadeFatura.setEditable(false);
        txtCidadeFatura.setText("cidade");
        txtCidadeFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeFaturaActionPerformed(evt);
            }
        });

        txtPaisFatura.setEditable(false);
        txtPaisFatura.setText("pais");

        txtEstadoFatura.setEditable(false);
        txtEstadoFatura.setText("estado");
        txtEstadoFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoFaturaActionPerformed(evt);
            }
        });

        txtCodigoPostalFatura.setEditable(false);
        txtCodigoPostalFatura.setText("cep");

        txtNumeroCartaoCredito.setEditable(false);
        txtNumeroCartaoCredito.setText("numeroCartaoCredito");

        txtContaCliente.setEditable(false);
        txtContaCliente.setText("contaCliente");

        txtCodigoConfirmacao.setEditable(false);
        txtCodigoConfirmacao.setText("codigoConfirmacao");
        txtCodigoConfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoConfirmacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPostalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaisFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogradouroFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtLogradouroFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCidadeFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstadoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaisFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoPostalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(txtNumeroCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(645, 345));

        txtNomeTransportadora.setEditable(false);
        txtNomeTransportadora.setText("nome");

        txtTaxaBaseTransportadora.setEditable(false);
        txtTaxaBaseTransportadora.setText("taxaBase");

        txtTaxaBaseEnvioTransportadora.setEditable(false);
        txtTaxaBaseEnvioTransportadora.setText("taxaEnvio");

        txtLogradouroEntrega.setEditable(false);
        txtLogradouroEntrega.setText("logradouro");

        txtCidadeEntrega.setEditable(false);
        txtCidadeEntrega.setText("cidade");

        txtEstadoEntrega.setEditable(false);
        txtEstadoEntrega.setText("estado");

        txtPaisEntrega.setEditable(false);
        txtPaisEntrega.setText("pais");

        txtCodigoPostalEntrega.setEditable(false);
        txtCodigoPostalEntrega.setText("codigoPostal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoPostalEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogradouroEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNomeTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtTaxaBaseTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtTaxaBaseEnvioTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCidadeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaisEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxaBaseTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxaBaseEnvioTransportadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txtLogradouroEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCidadeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEstadoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaisEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoPostalEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(0, 345));

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Código", "Nome", "Preço", "Cor", "Categoria", "Tamanho", "Peso"
            }
        ));
        jScrollPane3.setViewportView(tbProdutos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoConfirmacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoConfirmacaoActionPerformed

    private void txtEstadoFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoFaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoFaturaActionPerformed

    private void txtCidadeFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeFaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeFaturaActionPerformed

    private void txtPrimeiroNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimeiroNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimeiroNomeClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField txtCidadeEntrega;
    private javax.swing.JTextField txtCidadeFatura;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoConfirmacao;
    private javax.swing.JTextField txtCodigoPostalEntrega;
    private javax.swing.JTextField txtCodigoPostalFatura;
    private javax.swing.JTextField txtCodigoVendedor;
    private javax.swing.JTextField txtContaCliente;
    private javax.swing.JTextField txtDtPedido;
    private javax.swing.JTextField txtEstadoEntrega;
    private javax.swing.JTextField txtEstadoFatura;
    private javax.swing.JTextField txtLogradouroEntrega;
    private javax.swing.JTextField txtLogradouroFatura;
    private javax.swing.JTextField txtNomeDoMeioCliente;
    private javax.swing.JTextField txtNomeTransportadora;
    private javax.swing.JTextField txtNomeVendedor;
    private javax.swing.JTextField txtNumeroCartaoCredito;
    private javax.swing.JTextField txtPaisEntrega;
    private javax.swing.JTextField txtPaisFatura;
    private javax.swing.JTextField txtPrimeiroNomeCliente;
    private javax.swing.JTextField txtSobrenomeCliente;
    private javax.swing.JTextField txtSufixoCliente;
    private javax.swing.JTextField txtTaxaBaseEnvioTransportadora;
    private javax.swing.JTextField txtTaxaBaseTransportadora;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTratamentoCliente;
    // End of variables declaration//GEN-END:variables
}
